Vagrant.configure("2") do |config|
 config.vm.define :servidorFtp do |servidorFtp|
  servidorFtp.vm.box = "centos/stream8"
  servidorFtp.vm.network :private_network, ip: "209.191.100.2"
  servidorFtp.vm.hostname = "servidorFtp"
 end
 config.vm.define :firewall do |firewall|
  firewall.vm.box = "centos/stream8"
  firewall.vm.network :private_network, ip: "209.191.100.3"
  firewall.vm.network :private_network, ip: "192.168.100.3"
  firewall.vm.hostname = "firewall"
 end
end
