Vagrant.configure("2") do |config|
 config.vm.define :firewall do |firewall|
  firewall.vm.box = "centos/stream8"
  firewall.vm.network :private_network, ip: "192.168.56.3"
  firewall.vm.hostname = "firewall"
 end
end
